---
title: "BRT_air_quality_data"
author: "Abby Hanna"
date: "4/8/2020"
output: html_document
---

```{r}
library(readr)
library(stargazer)
library(tidyverse)
```

```{r sources of the data}


## General overview data collected on of atmospheric concentrations from: Belo Horizonte, Rio de Janeiro,Sao Paulo, and Grande Victoria. All cities have a BRT system (and has held at least one sports mega-event in the last decade) implemented except for Grande Victoria. It is important to note that Curitiba's is the first BRT system ever completed in 1978.

#### Data sources


#  precipitation_bra-csv: National Centers for Environmental Information (NCEI / NOAA)


belohorizonte_aq_weather_2015_csv <- read_delim("~/Desktop/eco project/belohorizonte_aq_weather_2015_csv.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)
View(belohorizonte_aq_weather_2015_csv)

## Source: http://www.feam.br/component/content/article/15/1753-belo-horizonte

## Belo Horizonte weather and air quality data from 2015. 

ap_sao_paulo_since2013 <- read_csv("~/Desktop/eco project/cetesb.csv")
View(ap_sao_paulo_since2013)

sao_paulo_2014_pollutants <- read_delim("~/Desktop/eco project/sao_paulo_2014_pollutants_csv.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)
View(sao_paulo_2014_pollutants)

## Source : https://www.atmos-chem-phys.net/17/11943/2017/acp-17-11943-2017.pdf 

## Closer look at pollutants in Sao Paulo in 2013 and 2014. 


RDJ_2016_aq <- read_csv("~/Desktop/eco project/2016RJ1 copy.csv.zip")
View(RDJ_2016_aq)

ES_2016_aq <- read_csv("~/Desktop/eco project/2016ES1.csv.zip")
View(ES_2016_aq)

##Source: http://energiaeambiente.org.br/ 

## Air quality data from Rio de Janeiro state (with city of Rio de Janeiro) and Espirito Santos (with city of Grande Vitória) in 2016. 
  

qa_gv_2014_csv <- read_delim("~/Desktop/eco project/qa_gv_2014_csv.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)
View(qa_gv_2014_csv)

## Source: https://iema.es.gov.br/qualidade-do-ar2

```

